const brand = require('./brand');
const { icon } = require('./icon');

const links = (page, listClasses = 'gap-x-4 gap-y-2') => `<ul class="flex flex-wrap items-center justify-center ${listClasses} text-[13.5px] text-white/75"><li><a href="legal.html#privacidad" class="hover:text-white transition-colors">Política de Privacidad</a></li><li><span class="text-white/30">·</span></li><li><a href="legal.html#terminos" class="hover:text-white transition-colors">Aviso Legal</a></li><li><span class="text-white/30">·</span></li><li><a href="legal.html#datos" class="hover:text-white transition-colors">Política de Datos</a></li><li><span class="text-white/30">·</span></li><li><a href="etica-legal.html"${page.footerCurrent === 'ethics' ? ' aria-current="page"' : ''} class="hover:text-white transition-colors">Ética Profesional</a></li></ul>`;

module.exports = function footer(page) {
  if (page.footer === 'extended') return `<footer class="bg-(--rose-dark) text-(--white)"><div class="mx-auto max-w-360 px-6 sm:px-14 lg:px-24 py-16"><div class="flex flex-col md:flex-row items-center justify-between gap-8 pb-10 border-b border-white/15"><p class="font-serif text-2xl text-center sm:text-left">Nos ponemos a su <span class="italic">disposición</span>.</p><a href="contact.html" class="inline-flex w-full sm:w-auto items-center justify-center gap-2 bg-(--white) text-(--rose-dark) text-[13px] tracking-wide font-semibold px-7 py-3 rounded-full hover:bg-(--beige-light) transition-colors">Agende su consulta ${icon('arrow-right', 'h-3 w-3')}</a></div><div class="flex flex-col md:flex-row items-center justify-between gap-6 pt-8">${brand('short', 'dark')}${links(page, 'gap-6')}<span class="text-xs italic font-serif text-(--rose-light)">Diseñado para la excelencia jurídica.</span></div></div></footer>`;
  return `<footer class="bg-(--rose-dark) border-t border-white/15"><div class="mx-auto max-w-360 px-6 sm:px-14 lg:px-24 py-8 flex flex-col md:flex-row items-center justify-between gap-6 text-center md:text-left">${brand('long', 'dark')}${links(page)}<span class="text-xs italic font-serif text-(--rose-light)">Diseñado para la excelencia jurídica.</span></div></footer>`;
};
