const { site, organizationJsonLd, escapeHtmlAttribute } = require('../data/site');

function jsonLd(canonical) {
  return `<script type="application/ld+json">\n${JSON.stringify({ '@context': 'https://schema.org', '@graph': [organizationJsonLd(canonical, 'LegalService', 'legalservice'), organizationJsonLd(canonical, 'LocalBusiness', 'localbusiness')] }, null, 2)}\n</script>`;
}

module.exports = function head(page) {
  const unsplash = page.preconnectUnsplash ? '\n<link rel="preconnect" href="https://images.unsplash.com" crossorigin>' : '';
  return `<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>${escapeHtmlAttribute(page.title)}</title>\n<meta name="description" content="${escapeHtmlAttribute(page.description)}">\n<meta name="author" content="${escapeHtmlAttribute(site.brandLongText)}">\n<meta name="robots" content="${escapeHtmlAttribute(page.robots)}">\n<link rel="canonical" href="${escapeHtmlAttribute(page.canonical)}">\n<link rel="icon" href="${escapeHtmlAttribute(site.brandMarkSvg)}" type="image/svg+xml">\n<meta property="og:locale" content="es_CL">\n<meta property="og:type" content="website">\n<meta property="og:site_name" content="${escapeHtmlAttribute(site.brandLongText)}">\n<meta property="og:title" content="${escapeHtmlAttribute(page.title)}">\n<meta property="og:description" content="${escapeHtmlAttribute(page.description)}">\n<meta property="og:url" content="${escapeHtmlAttribute(page.canonical)}">\n<meta property="og:image" content="${escapeHtmlAttribute(site.socialImage)}">\n<meta property="og:image:secure_url" content="${escapeHtmlAttribute(site.socialImage)}">\n<meta property="og:image:width" content="1200">\n<meta property="og:image:height" content="630">\n<meta property="og:image:alt" content="${escapeHtmlAttribute(site.socialImageAlt)}">\n<meta name="twitter:card" content="summary_large_image">\n<meta name="twitter:domain" content="${escapeHtmlAttribute(site.domain)}">\n<meta name="twitter:title" content="${escapeHtmlAttribute(page.title)}">\n<meta name="twitter:description" content="${escapeHtmlAttribute(page.description)}">\n<meta name="twitter:image" content="${escapeHtmlAttribute(site.socialImage)}">\n<meta name="twitter:image:alt" content="${escapeHtmlAttribute(site.socialImageAlt)}">${page.jsonLd ? `\n${jsonLd(page.canonical)}` : ''}\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin>\n<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>${unsplash}\n<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600&amp;family=Inter:wght@300;400;500;600&amp;display=swap">\n<link rel="stylesheet" href="assets/tailwind.css">\n<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha384-t1nt8BQoYMLFN5p42tRAtuAAFQaCQODekUVeKKZrEnEyp4H2R0RHFz0KWpmj7i8g" crossorigin="anonymous">\n<link rel="stylesheet" href="assets/site.css">\n</head>`;
};
